package com.jrt.invokeLot.dao;

import java.util.List;

import com.jrt.invokeLot.model.Advert;

public interface AdvertDAO {
    /**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table Advert
	 * @ibatorgenerated  Wed Nov 24 10:59:30 CST 2010
	 */
	int deleteByPrimaryKey(String id);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table Advert
	 * @ibatorgenerated  Wed Nov 24 10:59:30 CST 2010
	 */
	void insert(Advert record);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table Advert
	 * @ibatorgenerated  Wed Nov 24 10:59:30 CST 2010
	 */
	void insertSelective(Advert record);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table Advert
	 * @ibatorgenerated  Wed Nov 24 10:59:30 CST 2010
	 */
	Advert selectByPrimaryKey(String id);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table Advert
	 * @ibatorgenerated  Wed Nov 24 10:59:30 CST 2010
	 */
	int updateByPrimaryKeySelective(Advert record);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table Advert
	 * @ibatorgenerated  Wed Nov 24 10:59:30 CST 2010
	 */
	int updateByPrimaryKey(Advert record);

	/**
     * 查询页面上面广告 
     */
    List<Advert> getAdvert();
}