package com.jrt.invokeLot.dao;

import java.util.List;

import com.jrt.invokeLot.model.Category;

public interface CategoryDAO {

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table Category
	 * @ibatorgenerated  Wed Nov 24 10:59:30 CST 2010
	 */
	int deleteByPrimaryKey(Long id);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table Category
	 * @ibatorgenerated  Wed Nov 24 10:59:30 CST 2010
	 */
	void insert(Category record);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table Category
	 * @ibatorgenerated  Wed Nov 24 10:59:30 CST 2010
	 */
	void insertSelective(Category record);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table Category
	 * @ibatorgenerated  Wed Nov 24 10:59:30 CST 2010
	 */
	Category selectByPrimaryKey(Long id);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table Category
	 * @ibatorgenerated  Wed Nov 24 10:59:30 CST 2010
	 */
	int updateByPrimaryKeySelective(Category record);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table Category
	 * @ibatorgenerated  Wed Nov 24 10:59:30 CST 2010
	 */
	int updateByPrimaryKey(Category record);

	List<Category> selectCategoryByType(String type);
	Category selectCategoryByTypeAndId(String type, Long id) ;
	
	/**
	 * 
	 * @Title:  getCategoryByType
	 * @Description: 查询相同种类的新�?
	 * @param: type 种类id
	 * @return:   集合
	 * 
	 */
	public List<Category> getCategoryByType(String type,int categoryType);
	
	
}