package com.jrt.invokeLot.dao;

import com.jrt.invokeLot.model.Categorytype;

public interface CategorytypeDAO {

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table CategoryType
	 * @ibatorgenerated  Wed Nov 24 10:59:30 CST 2010
	 */
	int deleteByPrimaryKey(Long id);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table CategoryType
	 * @ibatorgenerated  Wed Nov 24 10:59:30 CST 2010
	 */
	void insert(Categorytype record);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table CategoryType
	 * @ibatorgenerated  Wed Nov 24 10:59:30 CST 2010
	 */
	void insertSelective(Categorytype record);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table CategoryType
	 * @ibatorgenerated  Wed Nov 24 10:59:30 CST 2010
	 */
	Categorytype selectByPrimaryKey(Long id);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table CategoryType
	 * @ibatorgenerated  Wed Nov 24 10:59:30 CST 2010
	 */
	int updateByPrimaryKeySelective(Categorytype record);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table CategoryType
	 * @ibatorgenerated  Wed Nov 24 10:59:30 CST 2010
	 */
	int updateByPrimaryKey(Categorytype record);
}