package com.jrt.invokeLot.model;

import java.util.Date;

public class Advert {

	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column Advert.id
	 * @ibatorgenerated  Wed Nov 24 10:59:30 CST 2010
	 */
	private String id;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column Advert.type
	 * @ibatorgenerated  Wed Nov 24 10:59:30 CST 2010
	 */
	private String type;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column Advert.notes
	 * @ibatorgenerated  Wed Nov 24 10:59:30 CST 2010
	 */
	private String notes;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column Advert.dateTime
	 * @ibatorgenerated  Wed Nov 24 10:59:30 CST 2010
	 */
	private Date dateTime;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column Advert.link
	 * @ibatorgenerated  Wed Nov 24 10:59:30 CST 2010
	 */
	private String link;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column Advert.picture
	 * @ibatorgenerated  Wed Nov 24 10:59:30 CST 2010
	 */
	private String picture;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column Advert.status
	 * @ibatorgenerated  Wed Nov 24 10:59:30 CST 2010
	 */
	private Integer status;

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column Advert.id
	 * @return  the value of Advert.id
	 * @ibatorgenerated  Wed Nov 24 10:59:30 CST 2010
	 */
	public String getId() {
		return id;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column Advert.id
	 * @param id  the value for Advert.id
	 * @ibatorgenerated  Wed Nov 24 10:59:30 CST 2010
	 */
	public void setId(String id) {
		this.id = id;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column Advert.type
	 * @return  the value of Advert.type
	 * @ibatorgenerated  Wed Nov 24 10:59:30 CST 2010
	 */
	public String getType() {
		return type;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column Advert.type
	 * @param type  the value for Advert.type
	 * @ibatorgenerated  Wed Nov 24 10:59:30 CST 2010
	 */
	public void setType(String type) {
		this.type = type;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column Advert.notes
	 * @return  the value of Advert.notes
	 * @ibatorgenerated  Wed Nov 24 10:59:30 CST 2010
	 */
	public String getNotes() {
		return notes;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column Advert.notes
	 * @param notes  the value for Advert.notes
	 * @ibatorgenerated  Wed Nov 24 10:59:30 CST 2010
	 */
	public void setNotes(String notes) {
		this.notes = notes;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column Advert.dateTime
	 * @return  the value of Advert.dateTime
	 * @ibatorgenerated  Wed Nov 24 10:59:30 CST 2010
	 */
	public Date getDateTime() {
		return dateTime;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column Advert.dateTime
	 * @param dateTime  the value for Advert.dateTime
	 * @ibatorgenerated  Wed Nov 24 10:59:30 CST 2010
	 */
	public void setDateTime(Date dateTime) {
		this.dateTime = dateTime;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column Advert.link
	 * @return  the value of Advert.link
	 * @ibatorgenerated  Wed Nov 24 10:59:30 CST 2010
	 */
	public String getLink() {
		return link;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column Advert.link
	 * @param link  the value for Advert.link
	 * @ibatorgenerated  Wed Nov 24 10:59:30 CST 2010
	 */
	public void setLink(String link) {
		this.link = link;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column Advert.picture
	 * @return  the value of Advert.picture
	 * @ibatorgenerated  Wed Nov 24 10:59:30 CST 2010
	 */
	public String getPicture() {
		return picture;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column Advert.picture
	 * @param picture  the value for Advert.picture
	 * @ibatorgenerated  Wed Nov 24 10:59:30 CST 2010
	 */
	public void setPicture(String picture) {
		this.picture = picture;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column Advert.status
	 * @return  the value of Advert.status
	 * @ibatorgenerated  Wed Nov 24 10:59:30 CST 2010
	 */
	public Integer getStatus() {
		return status;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column Advert.status
	 * @param status  the value for Advert.status
	 * @ibatorgenerated  Wed Nov 24 10:59:30 CST 2010
	 */
	public void setStatus(Integer status) {
		this.status = status;
	}
}