package com.jrt.invokeLot.model;

public class Categorytype {

	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column CategoryType.id
	 * @ibatorgenerated  Wed Nov 24 10:59:30 CST 2010
	 */
	private Long id;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column CategoryType.name
	 * @ibatorgenerated  Wed Nov 24 10:59:30 CST 2010
	 */
	private String name;

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column CategoryType.id
	 * @return  the value of CategoryType.id
	 * @ibatorgenerated  Wed Nov 24 10:59:30 CST 2010
	 */
	public Long getId() {
		return id;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column CategoryType.id
	 * @param id  the value for CategoryType.id
	 * @ibatorgenerated  Wed Nov 24 10:59:30 CST 2010
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column CategoryType.name
	 * @return  the value of CategoryType.name
	 * @ibatorgenerated  Wed Nov 24 10:59:30 CST 2010
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column CategoryType.name
	 * @param name  the value for CategoryType.name
	 * @ibatorgenerated  Wed Nov 24 10:59:30 CST 2010
	 */
	public void setName(String name) {
		this.name = name;
	}
}