package com.jrt.invokeLot.model;

public class Category {

	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column Category.id
	 * @ibatorgenerated  Wed Nov 24 10:59:30 CST 2010
	 */
	private Long id;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column Category.categoryName
	 * @ibatorgenerated  Wed Nov 24 10:59:30 CST 2010
	 */
	private String categoryName;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column Category.type
	 * @ibatorgenerated  Wed Nov 24 10:59:30 CST 2010
	 */
	private String type;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column Category.categoryType
	 * @ibatorgenerated  Wed Nov 24 10:59:30 CST 2010
	 */
	private Integer categoryType;

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column Category.id
	 * @return  the value of Category.id
	 * @ibatorgenerated  Wed Nov 24 10:59:30 CST 2010
	 */
	public Long getId() {
		return id;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column Category.id
	 * @param id  the value for Category.id
	 * @ibatorgenerated  Wed Nov 24 10:59:30 CST 2010
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column Category.categoryName
	 * @return  the value of Category.categoryName
	 * @ibatorgenerated  Wed Nov 24 10:59:30 CST 2010
	 */
	public String getCategoryName() {
		return categoryName;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column Category.categoryName
	 * @param categoryName  the value for Category.categoryName
	 * @ibatorgenerated  Wed Nov 24 10:59:30 CST 2010
	 */
	public void setCategoryName(String categoryName) {
		this.categoryName = categoryName;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column Category.type
	 * @return  the value of Category.type
	 * @ibatorgenerated  Wed Nov 24 10:59:30 CST 2010
	 */
	public String getType() {
		return type;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column Category.type
	 * @param type  the value for Category.type
	 * @ibatorgenerated  Wed Nov 24 10:59:30 CST 2010
	 */
	public void setType(String type) {
		this.type = type;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column Category.categoryType
	 * @return  the value of Category.categoryType
	 * @ibatorgenerated  Wed Nov 24 10:59:30 CST 2010
	 */
	public Integer getCategoryType() {
		return categoryType;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column Category.categoryType
	 * @param categoryType  the value for Category.categoryType
	 * @ibatorgenerated  Wed Nov 24 10:59:30 CST 2010
	 */
	public void setCategoryType(Integer categoryType) {
		this.categoryType = categoryType;
	}
}