package com.jrt.invokeLot.model;

public class News {

	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column News.id
	 * @ibatorgenerated  Wed Nov 24 10:59:30 CST 2010
	 */
	private Long id;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column News.pubDate
	 * @ibatorgenerated  Wed Nov 24 10:59:30 CST 2010
	 */
	private String pubDate;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column News.orderId
	 * @ibatorgenerated  Wed Nov 24 10:59:30 CST 2010
	 */
	private Integer orderId;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column News.userId
	 * @ibatorgenerated  Wed Nov 24 10:59:30 CST 2010
	 */
	private String userId;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column News.soruceFrom
	 * @ibatorgenerated  Wed Nov 24 10:59:30 CST 2010
	 */
	private String soruceFrom;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column News.checked
	 * @ibatorgenerated  Wed Nov 24 10:59:30 CST 2010
	 */
	private Integer checked;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column News.type
	 * @ibatorgenerated  Wed Nov 24 10:59:30 CST 2010
	 */
	private String type;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column News.categoryId
	 * @ibatorgenerated  Wed Nov 24 10:59:30 CST 2010
	 */
	private Long categoryId;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column News.channelId
	 * @ibatorgenerated  Wed Nov 24 10:59:30 CST 2010
	 */
	private Integer channelId;

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column News.id
	 * @return  the value of News.id
	 * @ibatorgenerated  Wed Nov 24 10:59:30 CST 2010
	 */
	public Long getId() {
		return id;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column News.id
	 * @param id  the value for News.id
	 * @ibatorgenerated  Wed Nov 24 10:59:30 CST 2010
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column News.pubDate
	 * @return  the value of News.pubDate
	 * @ibatorgenerated  Wed Nov 24 10:59:30 CST 2010
	 */
	public String getPubDate() {
		return pubDate;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column News.pubDate
	 * @param pubDate  the value for News.pubDate
	 * @ibatorgenerated  Wed Nov 24 10:59:30 CST 2010
	 */
	public void setPubDate(String pubDate) {
		this.pubDate = pubDate;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column News.orderId
	 * @return  the value of News.orderId
	 * @ibatorgenerated  Wed Nov 24 10:59:30 CST 2010
	 */
	public Integer getOrderId() {
		return orderId;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column News.orderId
	 * @param orderId  the value for News.orderId
	 * @ibatorgenerated  Wed Nov 24 10:59:30 CST 2010
	 */
	public void setOrderId(Integer orderId) {
		this.orderId = orderId;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column News.userId
	 * @return  the value of News.userId
	 * @ibatorgenerated  Wed Nov 24 10:59:30 CST 2010
	 */
	public String getUserId() {
		return userId;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column News.userId
	 * @param userId  the value for News.userId
	 * @ibatorgenerated  Wed Nov 24 10:59:30 CST 2010
	 */
	public void setUserId(String userId) {
		this.userId = userId;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column News.soruceFrom
	 * @return  the value of News.soruceFrom
	 * @ibatorgenerated  Wed Nov 24 10:59:30 CST 2010
	 */
	public String getSoruceFrom() {
		return soruceFrom;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column News.soruceFrom
	 * @param soruceFrom  the value for News.soruceFrom
	 * @ibatorgenerated  Wed Nov 24 10:59:30 CST 2010
	 */
	public void setSoruceFrom(String soruceFrom) {
		this.soruceFrom = soruceFrom;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column News.checked
	 * @return  the value of News.checked
	 * @ibatorgenerated  Wed Nov 24 10:59:30 CST 2010
	 */
	public Integer getChecked() {
		return checked;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column News.checked
	 * @param checked  the value for News.checked
	 * @ibatorgenerated  Wed Nov 24 10:59:30 CST 2010
	 */
	public void setChecked(Integer checked) {
		this.checked = checked;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column News.type
	 * @return  the value of News.type
	 * @ibatorgenerated  Wed Nov 24 10:59:30 CST 2010
	 */
	public String getType() {
		return type;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column News.type
	 * @param type  the value for News.type
	 * @ibatorgenerated  Wed Nov 24 10:59:30 CST 2010
	 */
	public void setType(String type) {
		this.type = type;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column News.categoryId
	 * @return  the value of News.categoryId
	 * @ibatorgenerated  Wed Nov 24 10:59:30 CST 2010
	 */
	public Long getCategoryId() {
		return categoryId;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column News.categoryId
	 * @param categoryId  the value for News.categoryId
	 * @ibatorgenerated  Wed Nov 24 10:59:30 CST 2010
	 */
	public void setCategoryId(Long categoryId) {
		this.categoryId = categoryId;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column News.channelId
	 * @return  the value of News.channelId
	 * @ibatorgenerated  Wed Nov 24 10:59:30 CST 2010
	 */
	public Integer getChannelId() {
		return channelId;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column News.channelId
	 * @param channelId  the value for News.channelId
	 * @ibatorgenerated  Wed Nov 24 10:59:30 CST 2010
	 */
	public void setChannelId(Integer channelId) {
		this.channelId = channelId;
	}
	
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column News.title
	 * @ibatorgenerated  Wed Nov 24 10:59:30 CST 2010
	 */
	private String title;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column News.title2
	 * @ibatorgenerated  Wed Nov 24 10:59:30 CST 2010
	 */
	private String title2;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column News.content
	 * @ibatorgenerated  Wed Nov 24 10:59:30 CST 2010
	 */
	private String content;

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column News.title
	 * @return  the value of News.title
	 * @ibatorgenerated  Wed Nov 24 10:59:30 CST 2010
	 */
	public String getTitle() {
		return title;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column News.title
	 * @param title  the value for News.title
	 * @ibatorgenerated  Wed Nov 24 10:59:30 CST 2010
	 */
	public void setTitle(String title) {
		this.title = title;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column News.title2
	 * @return  the value of News.title2
	 * @ibatorgenerated  Wed Nov 24 10:59:30 CST 2010
	 */
	public String getTitle2() {
		return title2;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column News.title2
	 * @param title2  the value for News.title2
	 * @ibatorgenerated  Wed Nov 24 10:59:30 CST 2010
	 */
	public void setTitle2(String title2) {
		this.title2 = title2;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column News.content
	 * @return  the value of News.content
	 * @ibatorgenerated  Wed Nov 24 10:59:30 CST 2010
	 */
	public String getContent() {
		return content;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column News.content
	 * @param content  the value for News.content
	 * @ibatorgenerated  Wed Nov 24 10:59:30 CST 2010
	 */
	public void setContent(String content) {
		this.content = content;
	}
}