package com.jrt.invokeLot.dao.impl;

import java.util.List;

import com.ibatis.dao.client.DaoManager;
import com.ibatis.dao.client.template.SqlMapDaoTemplate;
import com.jrt.invokeLot.dao.CategoryDAO;
import com.jrt.invokeLot.model.Category;

@SuppressWarnings("unchecked")
public class CategoryDAOImpl extends SqlMapDaoTemplate implements CategoryDAO {

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table Category
     *
     * @ibatorgenerated Wed Nov 17 14:09:12 CST 2010
     */
    public CategoryDAOImpl(DaoManager daoManager) {
        super(daoManager);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table Category
     *
     * @ibatorgenerated Wed Nov 17 14:09:12 CST 2010
     */
    public int deleteByPrimaryKey(Long id) {
        Category key = new Category();
        key.setId(id);
        int rows = delete("Category.ibatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table Category
     *
     * @ibatorgenerated Wed Nov 17 14:09:12 CST 2010
     */
    public void insert(Category record) {
        insert("Category.ibatorgenerated_insert", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table Category
     *
     * @ibatorgenerated Wed Nov 17 14:09:12 CST 2010
     */
    public void insertSelective(Category record) {
        insert("Category.ibatorgenerated_insertSelective", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table Category
     *
     * @ibatorgenerated Wed Nov 17 14:09:12 CST 2010
     */
    public Category selectByPrimaryKey(Long id) {
        Category key = new Category();
        key.setId(id);
        Category record = (Category) queryForObject("Category.ibatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table Category
     *
     * @ibatorgenerated Wed Nov 17 14:09:12 CST 2010
     */
    public int updateByPrimaryKeySelective(Category record) {
        int rows = update("Category.ibatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table Category
     *
     * @ibatorgenerated Wed Nov 17 14:09:12 CST 2010
     */
    public int updateByPrimaryKey(Category record) {
        int rows = update("Category.ibatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

	@Override
	/**
	 * 根据类型查询同类新闻
	 */
	public List<Category> getCategoryByType(String type,int categoryType) {
		Category category = new Category();
		category.setType(type);
		category.setCategoryType(categoryType);
		return (List<Category>)this.queryForList("Category.getCategoryByType",category);
	}

	/**
	 * 查询web网站上面的所有新闻
	 */
	@Override
	public List<Category> selectCategoryByType(String type) {
		Category category = new Category();
		category.setType(type);
		return (List<Category>)this.queryForList("Category.selectCategoryByType",category);
	}

	/**
	 * 根据id查询新闻
	 */
	@Override
	public Category selectCategoryByTypeAndId(String type, Long id) {
		Category category = new Category();
		category.setType(type);
		category.setId(id);
		return (Category)queryForObject("Category.selectCategoryByTypeAndId",category);
	}
}