package com.jrt.invokeLot.dao.impl;

import com.ibatis.dao.client.DaoManager;
import com.ibatis.dao.client.template.SqlMapDaoTemplate;
import com.jrt.invokeLot.dao.CategorytypeDAO;
import com.jrt.invokeLot.model.Categorytype;

public class CategorytypeDAOImpl extends SqlMapDaoTemplate implements CategorytypeDAO {

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table CategoryType
	 * @ibatorgenerated  Wed Nov 24 09:37:09 CST 2010
	 */
	public CategorytypeDAOImpl(DaoManager daoManager) {
		super(daoManager);
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table CategoryType
	 * @ibatorgenerated  Wed Nov 24 09:37:09 CST 2010
	 */
	public int deleteByPrimaryKey(Long id) {
		Categorytype key = new Categorytype();
		key.setId(id);
		int rows = delete("CategoryType.ibatorgenerated_deleteByPrimaryKey",
				key);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table CategoryType
	 * @ibatorgenerated  Wed Nov 24 09:37:09 CST 2010
	 */
	public void insert(Categorytype record) {
		insert("CategoryType.ibatorgenerated_insert", record);
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table CategoryType
	 * @ibatorgenerated  Wed Nov 24 09:37:09 CST 2010
	 */
	public void insertSelective(Categorytype record) {
		insert("CategoryType.ibatorgenerated_insertSelective", record);
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table CategoryType
	 * @ibatorgenerated  Wed Nov 24 09:37:09 CST 2010
	 */
	public Categorytype selectByPrimaryKey(Long id) {
		Categorytype key = new Categorytype();
		key.setId(id);
		Categorytype record = (Categorytype) queryForObject(
				"CategoryType.ibatorgenerated_selectByPrimaryKey", key);
		return record;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table CategoryType
	 * @ibatorgenerated  Wed Nov 24 09:37:09 CST 2010
	 */
	public int updateByPrimaryKeySelective(Categorytype record) {
		int rows = update(
				"CategoryType.ibatorgenerated_updateByPrimaryKeySelective",
				record);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table CategoryType
	 * @ibatorgenerated  Wed Nov 24 09:37:09 CST 2010
	 */
	public int updateByPrimaryKey(Categorytype record) {
		int rows = update("CategoryType.ibatorgenerated_updateByPrimaryKey",
				record);
		return rows;
	}
}