package com.jrt.invokeLot.dao.impl;

import java.util.HashMap;
import java.util.List;
import java.util.Map;

import com.ibatis.dao.client.DaoManager;
import com.ibatis.dao.client.template.SqlMapDaoTemplate;
import com.jrt.invokeLot.dao.NewsDAO;
import com.jrt.invokeLot.model.News;
import com.jrt.invokeLot.util.ListRange;

@SuppressWarnings("unchecked")
public class NewsDAOImpl extends SqlMapDaoTemplate implements NewsDAO {

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table News
     *
     * @ibatorgenerated Wed Nov 17 14:09:12 CST 2010
     */
    public NewsDAOImpl(DaoManager daoManager) {
        super(daoManager);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table News
     *
     * @ibatorgenerated Wed Nov 17 14:09:12 CST 2010
     */
    public int deleteByPrimaryKey(Long id) {
        News key = new News();
        key.setId(id);
        int rows = delete("News.ibatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table News
     *
     * @ibatorgenerated Wed Nov 17 14:09:12 CST 2010
     */
    public void insert(News record) {
        insert("News.ibatorgenerated_insert", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table News
     *
     * @ibatorgenerated Wed Nov 17 14:09:12 CST 2010
     */
    public void insertSelective(News record) {
        insert("News.ibatorgenerated_insertSelective", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table News
     *
     * @ibatorgenerated Wed Nov 17 14:09:12 CST 2010
     */
    public News selectByPrimaryKey(Long id) {
        News key = new News();
        key.setId(id);
        News record = (News) queryForObject("News.ibatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table News
     *
     * @ibatorgenerated Wed Nov 17 14:09:12 CST 2010
     */
    public int updateByPrimaryKeySelective(News record) {
        int rows = update("News.ibatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table News
     *
     * @ibatorgenerated Wed Nov 17 14:09:12 CST 2010
     */
    public int updateByPrimaryKey(News record) {
        int rows = update("News.ibatorgenerated_updateByPrimaryKey", record);
        return rows;
    }
    /**
     * 根据新闻类型查询共多少条新闻
     */
    public int getNewsCount(Long categoryId, String type){
    	News news = new News();
    	news.setCategoryId(categoryId);
    	news.setType(type);
    	return (Integer)this.queryForObject("News.getNewsCount",news);
    }
    
    /**
     * 根据新闻类型查询新闻内容按时间降序排列
     */
	
	@Override
	public List<News> getNewsListByPubDateDesc(Long categoryId, String type,int startRow, int pageSize) {
    	Map<Object, Object> map=new HashMap<Object,Object>();
        map.put("categoryId", categoryId);
        map.put("type", type);
        map.put("pageSize",pageSize);
        map.put("startRow", startRow);
        return (List<News>)this.queryForList("News.getNewsListByPubDateDesc",map);    
	}
	
	/**
     * 根据新闻类型查询新闻内容按时间升序排列
     */
	@Override
	public List<News> getNewsListByPubDateAsc(Long categoryId, String type,int startRow, int pageSize) {
    	Map<Object, Object> map=new HashMap<Object,Object>();
        map.put("categoryId", categoryId);
        map.put("type", type);
        map.put("pageSize",pageSize);
        map.put("startRow", startRow);
        return (List<News>)this.queryForList("News.getNewsListByPubDateAsc",map);    
	}
    
    /**
     * 根据id查询新闻内容
     */
    public News getNewsById(Long id,String type){
    	News news = new News();
    	news.setId(id);
    	news.setType(type);
    	return (News)this.queryForObject("News.selectNewsById",news);
    }

	@Override
	public ListRange<News> selectNewsListDesc(ListRange<News> range) {
		int count =(Integer)this.queryForObject("News.selectNewsCount",range);
        range.setCountrow(count);
        List<News> list=this.queryForList("News.selectNewsListDesc",range);
        range.setRecords(list);
        return range;
	}
	
	@Override
	public ListRange<News> selectNewsListAsc(ListRange<News> range) {
		int count =(Integer)this.queryForObject("News.selectNewsCount",range);
        range.setCountrow(count);
        List<News> list=this.queryForList("News.selectNewsListAsc",range);
        range.setRecords(list);
        return range;
	}
}